import sys;
import os;
import time;
import psutil;
import smtplib;
from email.mime.multipart import MIMEMultipart;
from email.mime.text import MIMEText;
from email.mime.base import MIMEBase;
from email import encoders;
from urllib import request;

def processDisplay(path):
	global newpath;
	if not os.path.exists(path):
		try:
			os.mkdir(path);
		except Exception:
			pass;

	line="-"*90;
	newpath=os.path.join(path, "Log.log");
	fobj=open(newpath, "w");
	fobj.write(line+"\n");
	fobj.write("Process Logger at : %s\n"%time.ctime());
	fobj.write(line+"\n");

	flag=0;
	try:
		for pobj in psutil.process_iter():
			flag=1;
			process=pobj.as_dict(attrs=['pid', 'name','username']);
			fobj.write("\n"+str(process));
	except Exception as e:
		fobj.write(str(e));

	if flag==1:
		print("Processes are Displayed to Log File");
	else:
		print("Error to Display Running Processes. Watch Log File ")
	

def is_connected():
	try:
		request.urlopen('https://gmail.com',timeout=1);
		return True;
	except request.URLError as err:
		return False;


def sendMail(toaddr):
	fromaddr=user.name();
	
	msg=MIMEMultipart();
	msg['From']=fromaddr;
	msg['To']=toaddr;
	msg['Subject']="Process Log File Attachment";
	body="Please find attached herewith a snapshot of running processes.\n\nThis mail is generated by Python Program.\n\n\nThanks and Regards\nDeepa Damji";
	
	msg.attach(MIMEText(body,'plain'));
	filename="Log.log";
	attachment=open(newpath,"rb");
	
	p=MIMEBase('application','octate-stream');
	p.set_payload((attachment).read());
	encoders.encode_base64(p);
	p.add_header('Content-Disposition', "attachment; filename=%s" % filename);
	msg.attach(p);
	
	s=smtplib.SMTP('smtp.gmail.com', 587);
	s.starttls();
	s.login(fromaddr,user.password());
	text=msg.as_string();
	
	s.sendmail(fromaddr,toaddr,text);
	s.quit();


def main():
	print("_"*78);
	print("\nAuthor     : Program is Developed by Deepa Damji");
	print("Description: Python Program to Display Processes in Log File of Given Directory");
	print("Date & Time: 2019-12-12 04:00:00");
	print("_"*78,"\n");

	try:
		connected=is_connected();
		if connected:
			starttime=time.time();
			processDisplay(sys.argv[1]);
			sendMail(sys.argv[2]);
			endtime=time.time();

			print("Took %s seconds to Evaluate"%(endtime-starttime));
		else:
			print("There is no internet connection");

	except Exception as e:
		print("Error: Invalid input",e);

	
if __name__ == "__main__":
	main();